version: "3"
services:
  fazentech-express-server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: fazentech-server
    volumes:
      - ./:/home/node/app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    expose:
      - "80"
    links:
      - mysql-db
  mysql-db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=fazentech_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root